user.service.url=http://${SERVICE_HOST_IP}:8081
auction.service.url=http://${SERVICE_HOST_IP}:8082
bidding.service.url=http://${SERVICE_HOST_IP}:8083
payment.service.url=http://${SERVICE_HOST_IP}:8084
websocket.url=ws://${SERVICE_HOST_IP}:8083